parameters:
#    coregen_theme_bootstrap.example.class: Coregen\ThemeBootstrapBundle\Example

services:
#    coregen_theme_bootstrap.example:
#        class: %coregen_theme_bootstrap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
